### ISSUE TITLE
Include fix for admin bar on sites that use Google Translate

### ISSUE THREAD

**Issue by brianjohnhanna** [stirling-brandworks/slab#20]
Google Translate adds some CSS that sets "position: relative" on the body which messes with the positioning of the WP admin bar on mobile. One fix that has been used in the past alleviates this issue:

```css
// Fix for admin header bar on mobile
// conflict with "position: relative;" added to body by Google Translate
@media screen and (max-width: 600px) {
  #wpadminbar {
    position: fixed;
  }
}
```
